version: '2'
services:
  app:
    image: dnunez24/magento2-ee
    links:
      - searchlb:search.magento.dev
      - mq:mq.magento.dev
  cron:
    image: dnunez24/magento2-ee
    links:
      - searchlb:search.magento.dev
      - mq:mq.magento.dev
  searchlb:
    image: nginx:1.10-alpine
    ports:
      - "9200:9200"
    links:
      - search:search.magento.dev
    volumes:
      - ./conf/elasticsearch/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./conf/elasticsearch/htpasswd:/etc/nginx/htpasswd
    environment:
      - TZ
    networks:
      back:
  search:
    image: elasticsearch:2
    volumes:
      - ./conf/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - search:/usr/share/elasticsearch/data
    networks:
      back:
  mq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
    volumes:
      - mq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE
      - RABBITMQ_DEFAULT_VHOST
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_HIPE_COMPILE
    networks:
      back:
volumes:
  search:
  mq:
