version: '2'
services:
  lb:
    image: haproxy:1-alpine
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      # Uncomment this and provide an SSL certificate file for SSL support
      # - ./conf/magento.pem:/etc/haproxy/certs/magento.pem
    networks:
      public:
        ipv4_address: 172.16.220.10
      front:
        ipv4_address: 172.16.221.10
  fpc:
    image: dnunez24/varnish
    volumes:
      - ./conf/varnish.vcl:/etc/varnish/default.vcl
    networks:
      front:
        ipv4_address: 172.16.221.20
  http:
    image: nginx:1.10-alpine
    volumes_from:
      - app
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./bin/nginx-start.sh:/start.sh
    networks:
      front:
        ipv4_address: 172.16.221.30
    command: [/start.sh]
  app:
    image: dnunez24/magento2-ee:latest
    volumes:
      - ee_app:/var/www/html
      - ./conf/env.php:/var/www/html/app/etc/env.php
      - ./conf/php.ini:/usr/local/etc/php/conf.d/magento.ini
    networks:
      front:
        ipv4_address: 172.16.221.40
      back:
        ipv4_address: 172.16.222.40
  cron:
    image: dnunez24/magento2-ee:latest
    volumes_from:
      - app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf/crontab:/var/spool/cron/crontabs/magento
    command: [/usr/sbin/crond, -f, -L, /dev/stdout]
    networks:
      back:
        ipv4_address: 172.16.222.50
  cache:
    image: redis:3.2-alpine
    volumes:
      - ee_cache:/data
      - ./conf/redis-cache.conf:/usr/local/etc/redis/redis.conf
    networks:
      back:
        ipv4_address: 172.16.222.60
    command: [redis-server, /usr/local/etc/redis/redis.conf]
    # echo never > /sys/kernel/mm/transparent_hugepage/enabled
    # vm.overcommit_memory = 1' to /etc/sysctl.conf
    # sysctl vm.overcommit_memory=1
    # TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128
  session:
    image: redis:3.2-alpine
    volumes:
      - ee_session:/data
      - ./conf/redis-session.conf:/usr/local/etc/redis/redis.conf
    networks:
      back:
        ipv4_address: 172.16.222.70
    command: [redis-server, /usr/local/etc/redis/redis.conf]
    # echo never > /sys/kernel/mm/transparent_hugepage/enabled
    # vm.overcommit_memory = 1' to /etc/sysctl.conf
    # sysctl vm.overcommit_memory=1
    # TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128
  search:
    image: elasticsearch:2
    ports:
      - "9200:9200"
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - search:/usr/share/elasticsearch/data
  mq:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  db:
    image: percona:5.6
    ports:
      - 3306:3306
    volumes:
      - ee_db:/var/lib/mysql
      # - ./conf/data.sql.gz:/docker-entrypoint-initdb.d/
    networks:
      back:
        ipv4_address: 172.16.222.80
volumes:
  ee_app:
  ee_db:
  ee_cache:
  ee_session:
networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.220.0/24
          gateway: 172.16.220.1
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.221.0/24
          gateway: 172.16.221.1
  back:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.222.0/24
          gateway: 172.16.222.1
